create extension if not exists pgcrypto;

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  public_id text unique not null,
  provider text not null check (provider in ('local', 'discord')),
  discord_id text unique,
  username text not null,
  password_hash text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create unique index if not exists users_local_username_unique
  on users (lower(username))
  where provider = 'local';

create table if not exists games (
  id bigint generated by default as identity primary key,
  pack integer not null default 1 check (pack between 1 and 5),
  video_url text default '',
  title text not null,
  size text default '',
  multiplayer text default '',
  genre text default '',
  description text default '',
  created_at timestamptz not null default now()
);

create table if not exists reactions (
  user_id uuid not null references users(id) on delete cascade,
  game_id bigint not null references games(id) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  primary key (user_id, game_id)
);

create table if not exists votes (
  user_id uuid not null references users(id) on delete cascade,
  game_id bigint not null references games(id) on delete cascade,
  choice text not null check (choice in ('yes', 'no')),
  created_at timestamptz not null default now(),
  primary key (user_id, game_id)
);

create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists games_pack_created_idx on games(pack, created_at desc);
create index if not exists reactions_game_idx on reactions(game_id);
create index if not exists votes_game_idx on votes(game_id);
create index if not exists chat_messages_created_idx on chat_messages(created_at desc);

with seed(pack, video_url, title, size, multiplayer, genre, description) as (
  values
    (1, 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'Пример игры: Neon Raid', '12 GB', '1-4 игрока', 'Action / Co-op', 'Шаблон карточки. Замени через админку на свою игру, трейлер или gameplay-видео.'),
    (1, 'https://www.youtube.com/embed/aqz-KE-bpKQ', 'Пример игры: Moon Cafe', '3 GB', '1-2 игрока', 'Casual', 'Легкая игра для вечернего созвона и мемов.'),
    (2, 'https://www.youtube.com/embed/ysz5S6PUM-U', 'Пример игры: Shadow Arena', '25 GB', '2-8 игроков', 'PvP', 'Пак 2 уже готов принимать игры.')
)
insert into games (pack, video_url, title, size, multiplayer, genre, description)
select pack, video_url, title, size, multiplayer, genre, description
from seed
where not exists (select 1 from games);
